name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Greet New Contributors
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.eventName === 'issues') {
              const issueBody = `**Hi there! 👋**  
              Thank you for opening this issue.  
              Our team will take a look as soon as possible and get back to you.  
              We truly appreciate your effort in improving **Pouranik**! 🌟`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: issueBody
              });
            }

            if (context.eventName === 'pull_request') {
              const prBody = `🎉 **Thanks for your pull request!**  
              We’ll review it shortly.  
              Your contribution means a lot to the project!✨`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: prBody
              });
            }

  first-time-contributor:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write

    steps:
      - name: Check if first-time contributor
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: context.actor,
              state: 'all'
            });

            const isFirstTime = pullRequests.length === 1;

            if (isFirstTime) {
              const welcomeMessage = `🎊 **Welcome to Pouranik!**  
              Thanks for making your first contribution. We're thrilled to have you here.  
              Feel free to explore more issues, suggest improvements, or ask questions.  
              ⭐ Don’t forget to star the repo to show your support!`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: welcomeMessage
              });
            }
